
listops = {
              "dataset":{
                  "train":96000,
                  "dev":2000,
                  "test":2000,
              },
              "model":{
                  "learn_pos_emb":True,
                  "tied_weights":False,
                  "embedding_dim":64, 
                  "transformer_dim":64, 
                  "transformer_hidden_dim":128, 
                  "head_dim":32, 
                  "num_head":2, 
                  "num_layers":4,
                  "vocab_size":32,
                  "max_seq_len":2000,
                  "dropout_prob":0.1,
                  "attention_dropout":0.1,
                  "pooling_mode":"MEAN",
                  "num_classes":10,
                  "block_size":64,
                  "batch_size":128, 
                  "density" : 0.04,
              },
              "training":{
                  "batch_size":128, 
                  "learning_rate":0.0008,
                  "warmup":1000,
                  "lr_decay":"linear",
                  "weight_decay":0,
                  "eval_frequency":500, 
                  "num_train_steps":30000,
                  "num_init_steps":1000,
                  "num_eval_steps":62,
                  "num_dense_train_steps" : 1000,
                  "patience":10, 
                  "attn_loss_scale":0.01,
              }
          }



retrieval={
              "dataset":{
                  "train":147086,
                  "dev":18090,
                  "test":17437,
              },
              "model":{
                  "learn_pos_emb":True,
                  "tied_weights":False,
                  "embedding_dim":64, 
                  "transformer_dim":64, 
                  "transformer_hidden_dim":128, 
                  "head_dim":32, 
                  "num_head":2, 
                  "num_layers":2,
                  "vocab_size":512,
                  "max_seq_len":4000,
                  "dropout_prob":0.1,
                  "attention_dropout":0.1,
                  "pooling_mode":"MEAN",
                  "block_size":64,
                  "num_classes": 2,
                  "batch_size":32,
                  "density" : 0.021,
              },
              "training":{
                  "batch_size":32, 
                  "learning_rate":0.0005,
                  "warmup":800,
                  "lr_decay":"linear",
                  "weight_decay":0,
                  "eval_frequency":200,
                  "num_train_steps":40000, 
                  # "num_train_steps" : 10000,
                  "num_init_steps":3000,
                  "num_eval_steps":300, 
                  # "num_dense_train_steps":2500,
                  "num_dense_train_steps" : 1000,
                  "patience":10, 
                  "attn_loss_scale":0.01,
              }
}

image={
        "dataset":{
            "train":45000,
            "dev":5000,
            "test":10000,
        },
        "model":{
            "learn_pos_emb":True,
            "tied_weights":False,
            "embedding_dim":64,
            "transformer_dim":64,
            "transformer_hidden_dim":128,
            "head_dim":32,
            "num_head":2,
            "num_layers":2,
            "vocab_size":256, 
            "max_seq_len":1024,
            "dropout_prob":0.1, 
            "attention_dropout":0.1,
            "pooling_mode":"MEAN",
            "num_classes": 10,
            "block_size":32,
            "batch_size": 512, 
            "density" : 0.05,
        },
        "training":{
            "batch_size":512, 
            # "learning_rate":0.0007, 
            "learning_rate":0.002,
            "warmup":175,
            "lr_decay":"linear",
            "weight_decay":0,
            "eval_frequency":500,  
            "num_train_steps":10000, 
            "num_init_steps":0,
            "num_eval_steps":20,
            "num_dense_train_steps":10,
            "attn_loss_scale":0.01,
            "skewness" : 1.7,
            "distance" : 1.3
        }
}

news1={
         "dataset":{
             "train":120000,
             "dev":7600,
             "test":7600,
         },
         "model":{
             "learn_pos_emb":True,
             "tied_weights":False,
             "embedding_dim":64, 
             "transformer_dim":64, 
             "transformer_hidden_dim":128, 
             "head_dim":32, 
             "num_head":2, 
             "num_layers":4,
             "vocab_size":512,
             "max_seq_len":1000, 
             "dropout_prob":0.1,
             "attention_dropout":0.1,
             "pooling_mode":"MEAN",
             "num_classes": 4,
             "block_size":32,
             "batch_size":512,
             "density" : 0.08,
         },
         "training":{
             "batch_size":512,
             #"learning_rate":0.0007,
             "learning_rate":0.0009,
             "warmup":80, 
             "lr_decay":"linear",
             "weight_decay":0,
             "eval_frequency":200, 
             # "num_train_steps":10000,
             "num_train_steps":30000,
             "num_init_steps":3000,
             "num_eval_steps":200, 
             "num_dense_train_steps":10000,
             "patience":10, 
             "attn_loss_scale":0.01,
             "skewness" : 1.7,
             "distance" : 1.3
         }
     }

yelp1={
         "dataset":{
             "train":560000,
             "dev":38000,
             "test":38000,
         },
         "model":{
             "learn_pos_emb":True,
             "tied_weights":False,
             "embedding_dim":64, 
             "transformer_dim":64, 
             "transformer_hidden_dim":128, 
             "head_dim":32, 
             "num_head":2, 
             "num_layers":4,
             "vocab_size":512,
             "max_seq_len":1000, 
             "dropout_prob":0.1,
             "attention_dropout":0.1,
             "pooling_mode":"MEAN",
             "num_classes": 2,
             "block_size":32,
             "batch_size":512,
             "density" : 0.05,
         },
         "training":{
             "batch_size":512,
             "learning_rate":0.0007,
             "warmup":80, 
             "lr_decay":"linear",
             "weight_decay":0,
             "eval_frequency":200, 
             # "num_train_steps" : 10000,
             "num_train_steps":30000,
             "num_init_steps":17000,
             "num_eval_steps":200, 
             "num_dense_train_steps":1000,
             "patience":10, 
             "attn_loss_scale":0.01,
             "skewness" : 1.7,
             "distance" : 1.3
         }
     }

nature={
              "dataset":{
                  "train":437513,
                  "dev":24426,
                  "test":149394,
              },
              "model":{
                  "learn_pos_emb":True,
                  "tied_weights":False,
                  "embedding_dim":64, 
                  "transformer_dim":64, 
                  "transformer_hidden_dim":128, 
                  "head_dim":32, 
                  "num_head":2, 
                  "num_layers":2,
                  "vocab_size":512,
                  "max_seq_len":1000,
                  "dropout_prob":0.1,
                  "attention_dropout":0.1,
                  "pooling_mode":"MEAN",
                  "num_classes": 14,
                  "block_size":32,
                  "batch_size":512,
                  "density" : 0.04,
              },
              "training":{
                  "batch_size":512, 
                  "learning_rate":0.003,
                  "warmup":800,
                  "lr_decay":"linear",
                  "weight_decay":0,
                  "eval_frequency":500,
                  "num_train_steps":10000, 
                  "num_init_steps":3000,
                  "num_eval_steps":300, 
                  "num_dense_train_steps":1000,
                  "patience":10, 
                  "attn_loss_scale":0.01,
                  "skewness" : 1.7,
                  "distnace" : 1.3
              }
          }

Config = {
    "lra-listops":listops,
    "lra-retrieval":retrieval,
    "lra-nature":nature,
    "lra-image":image,
    "lra-news1":news1,
    "lra-yelp1":yelp1,
}
